# Generated by Django 3.2.12 on 2022-06-13 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=254)),
                ('management', models.CharField(max_length=100)),
                ('male_big', models.IntegerField()),
                ('male_small', models.IntegerField()),
                ('male_disabled_big', models.IntegerField()),
                ('male_disabled_small', models.IntegerField()),
                ('male_child_big', models.IntegerField()),
                ('male_child_small', models.IntegerField()),
                ('female_big', models.IntegerField()),
                ('female_disabled_big', models.IntegerField()),
                ('female_child_big', models.IntegerField()),
                ('is_unisex', models.BooleanField()),
                ('is_24', models.BooleanField()),
                ('is_emergency', models.BooleanField()),
                ('is_cctv', models.BooleanField()),
                ('is_diaper', models.BooleanField()),
                ('like_users', models.ManyToManyField(blank=True, related_name='liked_toilets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_reviews', to=settings.AUTH_USER_MODEL)),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='toilets.toilet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
