# Generated by Django 3.2.12 on 2022-06-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=254)),
                ('management', models.CharField(max_length=100)),
                ('male_big', models.IntegerField()),
                ('male_small', models.IntegerField()),
                ('male_disabled_big', models.IntegerField()),
                ('male_disabled_small', models.IntegerField()),
                ('male_child_big', models.IntegerField()),
                ('male_child_small', models.IntegerField()),
                ('female_big', models.IntegerField()),
                ('female_disabled_big', models.IntegerField()),
                ('female_child_big', models.IntegerField()),
                ('is_unisex', models.BooleanField()),
                ('is_24', models.BooleanField()),
                ('is_emergency', models.BooleanField()),
                ('is_cctv', models.BooleanField()),
                ('is_diaper', models.BooleanField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('cosx', models.FloatField(default=0)),
                ('cosy', models.FloatField(default=0)),
                ('sinx', models.FloatField(default=0)),
                ('siny', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=100)),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='toilets.toilet')),
            ],
        ),
    ]
